gitlab:
  restart: always
  image: gitlab/gitlab-ce:9.1.2-ce.0
  ports:
    - "443"
    - "80"
    - "22"
  environment:
    - GITLAB_OMNIBUS_CONFIG: external_url 'https://gitlab.yourcompany.com'
  volumes:
    - /share/ContainerData/gitlab/data:/var/opt/gitlab
    - /share/ContainerData/gitlab/logs:/var/log/gitlab
    - /share/ContainerData/gitlab/config:/etc/gitlab
