gitlab:
  restart: always
  image: gitlab/gitlab-ce:9.1.2-ce.0
  ports:
    - "10443:443"
    - "10080:80"
    - "10022:22"
  volumes:
    - /share/ContainerData/gitlab/data:/var/opt/gitlab
    - /share/ContainerData/gitlab/logs:/var/log/gitlab
    - /share/ContainerData/gitlab/config:/etc/gitlab
